#!/usr/bin/env node
/**
 * Builds the single-file browser bundle: `src/browser.ts` and everything it
 * reaches — the three sibling packages' built `dist/` and one copy of zod —
 * into `dist-browser/workflow-helper.js` (ESM, ES2020, source map alongside).
 *
 *   npm run setup && npm run build:browser       # the siblings must be built first
 *   node scripts/build-browser.mjs --minify       # smaller, for vendoring
 *
 * A Node script rather than a shell one, so it runs unchanged on Windows.
 * Two guards make a green build meaningful:
 *
 *   - platform "browser": esbuild FAILS on any `node:` import, so success
 *     proves nothing Node-only leaked into the browser entry;
 *   - one zod: each sibling has its own node_modules/zod, and esbuild
 *     follows the `file:` symlinks to real paths, so without the plugin
 *     below the bundle would carry three copies. The plugin resolves every
 *     `zod` import from the preprocessor's folder, and the metafile check
 *     fails the build if more than one copy still got in. All three pin the
 *     same zod range, and Node already mixes the three copies today.
 */
import { build } from "esbuild";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";

const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PREPROCESSOR_DIR = resolve(PACKAGE_ROOT, "..", "preprocessor");

export const DEFAULT_OUTFILE = "dist-browser/workflow-helper.js";

/** Resolve every `zod` import from one place, so the bundle holds one copy. */
function dedupeZod() {
  return {
    name: "dedupe-zod",
    setup(build) {
      build.onResolve({ filter: /^zod(\/|$)/ }, async (args) => {
        if (args.pluginData?.deduped) return undefined;
        const result = await build.resolve(args.path, {
          kind: args.kind,
          resolveDir: PREPROCESSOR_DIR,
          pluginData: { deduped: true },
        });
        return { path: result.path, namespace: result.namespace, errors: result.errors };
      });
    },
  };
}

/** The distinct `node_modules/zod` directories that ended up in the bundle. */
export function zodCopies(metafile) {
  const dirs = new Set();
  for (const input of Object.keys(metafile.inputs)) {
    const match = /^(.*node_modules[\\/]zod)[\\/]/.exec(input);
    if (match) dirs.add(match[1]);
  }
  return [...dirs].sort();
}

function gitSha() {
  try {
    return execFileSync("git", ["rev-parse", "--short", "HEAD"], {
      cwd: PACKAGE_ROOT,
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
  } catch {
    return "unknown";
  }
}

/**
 * Build the bundle. `write: false` keeps the output in memory (`js`,
 * `outputFiles`) for tests. Throws on any esbuild error and when more than
 * one copy of zod got in.
 */
export async function buildBrowserBundle(options = {}) {
  const { outfile = DEFAULT_OUTFILE, minify = false, write = true } = options;
  const { version } = JSON.parse(readFileSync(resolve(PACKAGE_ROOT, "package.json"), "utf8"));
  const banner =
    `/* workflow-helper ${version} ${gitSha()} ${new Date().toISOString()} ` +
    "— generated by pipeline/scripts/build-browser.mjs, do not edit */";

  const result = await build({
    absWorkingDir: PACKAGE_ROOT,
    entryPoints: ["src/browser.ts"],
    outfile,
    bundle: true,
    format: "esm",
    platform: "browser",
    target: ["es2020"],
    sourcemap: true,
    legalComments: "eof",
    minify,
    metafile: true,
    write,
    banner: { js: banner },
    plugins: [dedupeZod()],
    logLevel: "silent",
  });

  const copies = zodCopies(result.metafile);
  if (copies.length !== 1) {
    throw new Error(
      `expected exactly one copy of zod in the bundle, found ${copies.length}:\n  ${copies.join("\n  ")}`,
    );
  }

  const js = write
    ? readFileSync(resolve(PACKAGE_ROOT, outfile))
    : Buffer.from(result.outputFiles.find((f) => f.path.endsWith(".js")).contents);
  return {
    outfile: resolve(PACKAGE_ROOT, outfile),
    bytes: js.length,
    gzipBytes: gzipSync(js).length,
    zodDir: copies[0],
    warnings: result.warnings,
    metafile: result.metafile,
    outputFiles: result.outputFiles,
    js,
  };
}

const kib = (n) => `${(n / 1024).toFixed(1)} KiB`;

function invokedDirectly() {
  if (!process.argv[1]) return false;
  const a = resolve(process.argv[1]);
  const b = fileURLToPath(import.meta.url);
  return process.platform === "win32" ? a.toLowerCase() === b.toLowerCase() : a === b;
}

if (invokedDirectly()) {
  const minify = process.argv.includes("--minify");
  try {
    const out = await buildBrowserBundle({ minify });
    for (const warning of out.warnings) console.warn(`warning: ${warning.text}`);
    console.log(
      `${relative(PACKAGE_ROOT, out.outfile)}  ${kib(out.bytes)} raw, ${kib(out.gzipBytes)} gzipped` +
        (minify ? " (minified)" : ""),
    );
    console.log(`zod: one copy, from ${relative(PACKAGE_ROOT, out.zodDir)}`);
  } catch (err) {
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  }
}
